### ISSUE TITLE
TravisCI build failing with : source package has two conflicting values

### ISSUE THREAD

**Issue by babluboy** [harisvsulaiman/element-build#1]
Hi,
I used your script, however the build is failing with:
```
dpkg-source --before-build flightcheck
dpkg-source: warning: unknown information field 'Standards-Version' in input data in package's section of control info file
dpkg-source: error: source package has two conflicting values - com.github.babluboy.bookworm and bookworm
dpkg-buildpackage: error: dpkg-source --before-build flightcheck gave error exit status 2
The command "wget -O- https://raw.githubusercontent.com/harisvsulaiman/element-build/master/script.sh | sh -" exited with 2.
Done. Your build exited with 1.
```

Debian Control file: [control](https://github.com/babluboy/bookworm/blob/master/debian/control)
Travis CI Log at: [Build #44](https://travis-ci.org/babluboy/bookworm/builds/286150128)

Will be great if you can help debug the issue. Let me know in case you need further info.

**Comment by harisvsulaiman** [comment]
@babluboy This seems to be an issue with conflicting package names in the changelog and control files.This PR https://github.com/babluboy/bookworm/pull/128 Solves the issue.

**Comment by babluboy** [comment]
many thanks - I have accepted the PR
