### ISSUE TITLE
Q: can it be used with meson?

### ISSUE THREAD

**Issue by artemanufrij** [harisvsulaiman/element-build#3]
Hey @harisvsulaiman I use your script for all my projects. I have plans to move from cmake to meson. Would the script work with meson?

**Comment by harisvsulaiman** [comment]
@artemanufrij yes, it does. I have used it with the meson build system.
Btw these are the apps using it right now.
https://github.com/search?o=desc&q=wget+-O-+https%3A%2F%2Fraw.githubusercontent.com%2Fharisvsulaiman%2Felement-build%2Fmaster%2Fscript.sh+%7C+sh+-&s=indexed&type=Code&utf8=✓

**Comment by artemanufrij** [comment]
Ok. Thanks for the answer
